setup:
  proxcli:
    path: /home/david/Documents/proxcli/venv/bin/proxcli
provision_template:
  count: 2
  disk_size: "30G"
  target: "pve2"
  disk_storage: "b4papp"
  memory: 2048
  cores: 2
  clone: 100
  block: true
  full_clone: true
  user: "system"
  password: "system"
  sshkey: "~/.ssh/id_rsa.pub"
  ipconfig: "ip=dhcp"
  tags:
    - "qemu"
    - "lab"
  disk_device: "virtio0"
  strategy: "spread"
  nodes: pve1,pve2,pve3
ha_groups_template:
  nodes: pve1,pve2,pve3
  restricted: false
  nofailback: true
  max_restart: 3
  max_relocate: 3
provision_instances:
  movie-web-prod-01:
    ha_groups:
      movie-web:
    instances:
      movie-web:
        desc: "movie web"
        count: 1
        memory: 4096
        cores: 4
        disk_storage: "b4papp"
        ha_group: "movie-web"
        tags:
          - "prod"
          - "movie-web"
          - "media"
  k3s-dev-01:
    ha_groups:
      master:
      node:
        nodes: "pve1,pve2"
    instances:
      master:
        desc: "control plane"
        count: 3
        ha_group: "master"
        memory: 4096
        cores: 4
        disk_storage: "b4pstorage"
        tags:
          - "dev"
          - "kubernetes"
          - "k3s"
          - "lab"
          - "master"
          - "k3s_cluster"
      node:
        desc: "node"
        count: 4
        ha_group: "node"
        memory: 4096
        cores: 4
        disk_storage: "b4papp"
        nodes: "pve1,pve2"
        tags:
          - "dev"
          - "kubernetes"
          - "k3s"
          - "lab"
          - "node"
          - "k3s_cluster"          
  nexus-prod-01:
    ha_groups:
      nexus:
    instances:
      nexus:
        desc: "nexus repository server"
        count: 1
        ha_group: "nexus"
        memory: 8198
        cores: 4
        disk_size: "60G"
        tags:
          - "prod"
          - "nexus"
          - "lab"
  grafana-dev-01:
    ha_groups:
      grafana:
      lb:
      db:
        nodes: pve1,pve2
    instances:
      grafana:
        desc: "grafana application"
        count: 3 
        ha_group: "grafana" 
        tags:
          - "grafana"
          - "grafana-server"
          - "metrics"
          - "lab"
          - "dev"
      lb:
        desc: "load balancers"
        count: 2 
        ha_group: "lb" 
        tags:
          - "grafana"
          - "load-balancer"
          - "keepalived"
          - "haproxy"
          - "metrics"
          - "lab"
          - "dev"
      db:
        desc: "database"
        count: 3
        nodes: pve1,pve2
        cores: 4
        memory: 4096 
        ha_group: "db" 
        tags:
          - "grafana"
          - "database"
          - "mariadb"
          - "metrics"
          - "lab"
          - "dev"