setup:
  proxcli:
    path: /home/david/Documents/proxcli/venv/bin/proxcli

provision_template:
  enable: true
  count: 1
  target: "pve2"
  clone: 100
  full_clone: true
  user: "system"
  password: "system"
  sshkey: "~/.ssh/id_rsa.pub"
  ipconfig: "ip=dhcp"
  block: true
  full_clone: true
  tags:
    - "qemu"
  disk_storage: "b4papp"
  disk_device: "virtio0"
  disk_size: "30G"
  cores: 2
  strategy: "spread"
  nodes: pve1,pve2,pve3
  memory: 2048
provision_instances:
  grafana-prod-01:
    ha_groups:
      server:
        nodes: pve1,pve2
        restricted: false
        nofailback: true
        max_restart: 3
        max_relocate: 3
      db:
        nodes: pve1,pve2
        restricted: false
        nofailback: true
        max_restart: 3
        max_relocate: 3
      lb:
        nodes: pve1,pve2,pve3
        restricted: false
        nofailback: true
        max_restart: 3
        max_relocate: 3
    instances:
      server:
        desc: "grafana server"
        count: 3
        ha_group: "server"
        nodes: pve1,pve2
        tags: 
          - "grafana"
          - "grafana-server"
          - "metrics"
          - "lab"
      db:
        desc: "grafana database"
        count: 3
        ha_group: "db"
        nodes: pve1,pve2
        tags: 
          - "grafana"
          - "grafana-db"
          - "metrics"
          - "lab"
      lb:
        desc: "grafana load balancer"
        count: 3
        ha_group: "lb"
        tags: 
          - "grafana"
          - "grafana-lb"
          - "metrics"
          - "lab"
  test-01:
    ha_groups:
      server:
        nodes: pve1,pve2
        restricted: false
        nofailback: true
        max_restart: 3
        max_relocate: 3
    instances:
      server:
        nodes: pve1,pve2
        desc: "test server"
        count: 2
        disk_size: "30G"
        ha_group: "server"
        tags: 
          - "lab"
