versions:

setup:
  proxcli:
    path: /home/david/Documents/proxcli/venv/bin/proxcli
  proxmox:
    pm_user: "root@pam"
    pm_password: "dfgdfg"
    nodes: 
      - 192.168.1.101
      - 192.168.1.102
      - 192.168.1.103
provision_template:
  enable: true
  count: 1
  target: "pve2"
  clone: 100
  full_clone: true
  user: "system"
  password: "system"
  sshkey: "~/.ssh/id_rsa.pub"
  ipconfig: "ip=dhcp"
  tags:
    - "qemu"
  disk_storage: "b4papp"
  disk_size: "30G"
  cores: 2
  strategy: "spread"
  nodes: pve1,pve2,pve3
  memory: 2048
provision_instances:
  grafana-prod-01:
    ha_groups:
      - name: controlplanes
        nodes: pve1,pve2,pve3
        restricted: false
        nofailback: true
      - name: workers
        nodes: pve1,pve2,pve3
        restricted: false
        nofailback: true
    instances:
      - name: "server"
        desc: "grafana server"
        count: 3
        tags: 
          - "grafana"
          - "grafana-server"
          - "metrics"
          - "lab"
      - name: "db"
        desc: "grafana database"
        count: 3
        tags: 
          - "grafana"
          - "grafana-db"
          - "metrics"
          - "lab"
      - name: "lb"
        desc: "grafana load balancer"
        count: 3
        tags: 
          - "grafana"
          - "grafana-lb"
          - "metrics"
          - "lab"

  k3s-prod-01:
    instances:
      - name: "controlplane"
        desc: "control plane"
        count: 3
        tags: 
          - "k3s"
          - "controlplane"
          - "kubernetes"
          - "lab"
      - name: "worker"
        desc: "worker"
        count: 6
        tags: 
          - "k3s"
          - "worker"
          - "kubernetes"
          - "lab"
